group=com.yeowool
version=1.0.0-SNAPSHOT

paperApiVersion=1.21.4-R0.1-SNAPSHOT
velocityApiVersion=3.4.0-SNAPSHOT

hikariVersion=5.1.0
mysqlConnectorVersion=8.4.0
caffeineVersion=3.1.8

vaultApiVersion=1.7
citizensVersion=2.0.43-SNAPSHOT
itemsAdderApiVersion=3.6.1
placeholderApiVersion=2.12.3

junitVersion=5.10.3
